import { apiSlice } from "./apiSlice";
import { Branch } from "../slices/branchSlice";

// Updated interface - removed 'id' since it's auto-generated by backend
export interface CreateBranchRequest {
  branchName: string;
  address: string;
  phone: string;
  email: string;
  hours: {
    weekdays: string;
    saturday: string;
    sunday: string;
  };
  staff?: Array<{
    name: string;
    position: string;
  }>;
}

// Interface for updating branch (still needs id in URL params)
export interface UpdateBranchRequest {
  id: string; // This is for the URL parameter
  data: Partial<Omit<CreateBranchRequest, "id">>; // Exclude id from update data
}

export const branchApi = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    getBranches: builder.query<
      { success: boolean; count: number; data: Branch[] },
      void
    >({
      query: () => ({
        url: "/branch",
        method: "GET",
      }),
      providesTags: ["Branch"],
    }),
    getBranchById: builder.query<{ success: boolean; data: Branch }, string>({
      query: (id) => ({
        url: `/branch/${id}`,
        method: "GET",
      }),
      providesTags: (_result, _error, id) => [{ type: "Branch", id }],
    }),
    createBranch: builder.mutation<
      { success: boolean; data: Branch; message: string },
      CreateBranchRequest
    >({
      query: (branchData) => ({
        url: "/branch",
        method: "POST",
        body: branchData,
      }),
      invalidatesTags: ["Branch"],
    }),
    updateBranch: builder.mutation<
      { success: boolean; data: Branch },
      UpdateBranchRequest
    >({
      query: ({ id, data }) => ({
        url: `/branch/${id}`,
        method: "PUT",
        body: data,
      }),
      invalidatesTags: (_result, _error, { id }) => [{ type: "Branch", id }],
    }),
    deleteBranch: builder.mutation<{ success: boolean }, string>({
      query: (id) => ({
        url: `/branch/${id}`,
        method: "DELETE",
      }),
      invalidatesTags: ["Branch"],
    }),
  }),
});

export const {
  useGetBranchesQuery,
  useGetBranchByIdQuery,
  useCreateBranchMutation,
  useUpdateBranchMutation,
  useDeleteBranchMutation,
} = branchApi;
